RECIPES_0_PATH = "Files/honestcooking_all_recipes.csv"
RECIPES_PATH = "Files/honestcooking_all_recipes_cleaned.csv"
PARSED_PATH = "Files/honestcooking_all_recipes_parsed.csv"
TFIDF_ENCODING_PATH = "Files/tfidf_encode.pkl"
TFIDF_MODEL_PATH = "Files/tfidf_model.pkl"
